### ISSUE TITLE
Get password count for particular hash

### ISSUE THREAD

**Issue by GSpecDrum** [timglabisch/easypwned#2]
Hi!

Thanks for the docker image! It's great! :-)

Does it have or planned posibility to get password count for particular hash?

**Comment by timglabisch** [comment]
No, it's not on the roadmap. the problem is that it is simply not possible by using a bloom filter. 
Can you give me more background on what this is relevant to in your case? maybe there is another approach.

**Comment by GSpecDrum** [comment]
I'm afraid that there isn't. Because logic of our app relies on how much times password was pwned to show a message asking him to change it. It comes from business side.:-)

**Comment by timglabisch** [comment]
@GSpecDrum You could create a Bloom filter that omits all passwords that have not been pwned often enough. May this would work? but why do you use this threshold at all? pwned is pwned or?
