### ISSUE TITLE
Server API question - why the /pw endpoint?

### ISSUE THREAD

**Issue by tmpfs** [timglabisch/easypwned#5]
Hi,

Thanks for this, I just used the downloader and it's really useful - I was dreading using the .NET version!

I wonder what the point of exposing an endpoint (`/pw`) that allows the user to submit a password to query the database is? I can't think of a valid reason for this and from my PoV it would make sense to only offer the hashed endpoint or am I missing something?

**Comment by timglabisch** [comment]
it's just for quick testing. you should best use post + hash.
